apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app.kubernetes.io/name: mysqldb
    app.kubernetes.io/component: backend
spec:
  ports:
    - name: mysqldb
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app.kubernetes.io/name: mysqldb
    app.kubernetes.io/component: backend
